apiVersion: minectl.ediri.io/v1alpha1
kind: MinecraftServer
metadata:
  name: minecraft-server
spec:
  monitoring:
    enabled: false
  server:
    cloud: aws
    region: eu-central-1
    size: t3.xlarge
    ssh:
      port: 22
      publickeyfile: "/Users/dirien/Tools/repos/stackit-minecraft/minecraft/ssh/minecraft.pub"
      fail2ban:
        bantime: 1000
        maxretry: 3
    port: 25565
  minecraft:
    java:
      openjdk: 17
      xmx: 2G
      xms: 2G
      rcon:
        password: test
        port: 25575
        enabled: true
        broadcast: true
    edition: java
    version: 1.19.3
    eula: true
    properties: |
      allow-flight=false
      allow-nether=true
      broadcast-console-to-ops=true
      broadcast-rcon-to-ops=true
      difficulty=easy
      enable-command-block=false
      enable-jmx-monitoring=false
      enable-query=false
      enable-rcon=false
      enable-status=true
      enforce-secure-profile=true
      enforce-whitelist=false
      entity-broadcast-range-percentage=100
      force-gamemode=false
      function-permission-level=2
      gamemode=survival
      generate-structures=true
      generator-settings={}
      hardcore=false
      hide-online-players=false
      level-name=world
      level-seed=minectlrocks
      level-type=minecraft\:normal
      max-chained-neighbor-updates=1000000
      max-players=20
      max-tick-time=60000
      max-world-size=29999984
      motd=\u00A76AWS \u00A7rMinecraft --- \u00A76Java \u00A7redition
      network-compression-threshold=256
      online-mode=true
      op-permission-level=4
      player-idle-timeout=0
      prevent-proxy-connections=false
      previews-chat=false
      pvp=true
      query.port=25565
      rate-limit=0
      rcon.password=
      rcon.port=25575
      require-resource-pack=false
      resource-pack=
      resource-pack-prompt=
      resource-pack-sha1=
      server-ip=
      server-port=25565
      simulation-distance=10
      spawn-animals=true
      spawn-monsters=true
      spawn-npcs=true
      spawn-protection=16
      sync-chunk-writes=true
      text-filtering-config=
      use-native-transport=true
      view-distance=10
      white-list=false
