apiVersion: minectl.ediri.io/v1alpha1
kind: MinecraftProxy
metadata:
  name: minecraft-proxy
spec:
  server:
    cloud: do
    region: fra1
    size: s-1vcpu-1gb
    ssh:
      port: 22
      publickeyfile: "/Users/dirien/Tools/repos/stackit-minecraft/minecraft/ssh/minecraft.pub"
      fail2ban:
        bantime: 1000
        maxretry: 3
    port: 25577
  proxy:
    java:
      openjdk: 16
      xmx: 512M
      xms: 512M
      rcon:
        password: test
        port: 25575
        enabled: true
        broadcast: true
    type: velocity
    version: 3.1.1-98