name: build-binary

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: 0
      - uses: actions/cache@35dd74a1a0674200316fa20212ce5036e0d9fc7f
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Go
        uses: actions/setup-go@44e221478fc6847752e5c574fc7a7b3247b00fbf
        with:
          go-version: 1.17
      - name: Tests
        run: |
          make test coverage
  release:
    permissions:
      id-token: write
      packages: write
    needs: build
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
      UPX_VERSION: "3.96"
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
      - name: Docker Login
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Set up Go
        uses: actions/setup-go@44e221478fc6847752e5c574fc7a7b3247b00fbf
        with:
          go-version: 1.17
      - uses: actions/cache@35dd74a1a0674200316fa20212ce5036e0d9fc7f
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: download upx
        run: |
          cd /tmp
          wget https://github.com/upx/upx/releases/download/v$UPX_VERSION/upx-$UPX_VERSION-amd64_linux.tar.xz
          tar xvf upx-$UPX_VERSION-amd64_linux.tar.xz
          sudo mv upx-$UPX_VERSION-amd64_linux/upx /usr/local/sbin
        shell: bash
      - uses: sigstore/cosign-installer@116dc6872c0a067bcb78758f18955414cdbf918f
      - uses: anchore/sbom-action/download-syft@3626d7d7b13e87ee6c6f9ded3940dea05a3967bc
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@a80c8fd82d21711db1dd61f87fc80d31b495b1fd
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}